### ISSUE TITLE
Local fulfillment 

### ISSUE THREAD

**Issue by Tyrian81** [LoekSangers/LoekSangers#1]
Dear Loek,

First off, I don't quite know if this is the right channel to contact you ?

I filled in my local fulfillment in actions console , and controls via  google assistant still work as expected.

Not quite knowing if its using the cloud or doing local commands, I could set my nest hub to local mode by doing "Hey Google, force local."  in this mode I can switch lights on/off on its screen , but voice actions do not work ?

I am using Home Assistant 2021.12.10

Kind regards,

Martijn

**Comment by LoekSangers** [comment]
Hello Martijn,

I think the proper place for this issue would be on the Home Assistant repository directly, as this is issue is related to that repository. The short answer as to why as that I believe this feature is not yet in the release. I expect it to be included in 2022.01.01/02 (not sure what the naming convention is, but the release that should happen in early February). 

Depending on your skill level you will have to wait, or can manually make the changes done in: https://github.com/home-assistant/core/pull/63218 to get this funtionality.

Kind regards,
Loek
